name: Build and Release

on:
    workflow_dispatch:
        inputs:
            tag:
                description: "Release tag"
                required: true
                type: string
            release_name:
                description: "Release name"
                required: true
                type: string

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Package Files
              run: |
                  bun run pack

            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  tag: ${{ inputs.tag }}
                  name: ${{ inputs.release_name }}
                  artifacts: "dist/*"
                  allowUpdates: true
                  removeArtifacts: true
                  replacesArtifacts: true
                  makeLatest: true
                  body: |
                      **Tag:** `${{ inputs.tag }}`
                      **Commit:** ${{ github.sha }}
                  token: ${{ secrets.GITHUB_TOKEN }}